version: '3'

volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  web: &app_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - app-gems:/usr/local/bundle
    depends_on:
      - db
      - rabbitmq
    stdin_open: true
    environment: &app_environment
      RACK_ENV: development
      RAILS_ENV: development
